test commit5

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -72,6 +72,18 @@ do
 
   if [[ " ${allowed_extensions[@]} " =~ " ${current_changes} " ]]; then
     echo "fourth"
+    while read local_ref local_sha remote_ref remote_sha;
+    do
+        CHANGED_FILES=$(git diff --name-only $local_sha $remote_sha | grep '\(cpp\|h\)$')
+        if [ ! -z "$CHANGED_FILES" -a "$CHANGED_FILES" != " " ]; then
+            echo $CHANGED_FILES
+            # RET=$?
+            # if [ $RET -ne 0 ]; then
+            #     echo "There is error(s) from style-check. Please fix them before push to the repo."
+            #     exit $RET
+            # fi
+        fi
+    done
     # do_exit
     exit 0
   fi
